[workspace]
resolver = "3"
members = ["api","core"]

[workspace.package]
edition = "2024"
version = "0.1.0"
authors = ["beep <contact@beep.ovh>"]
license = "Apache-2.0"

[workspace.dependencies]
thiserror = "2.0.17"
